### ISSUE TITLE
Bot cannot be able to claim missions eventhough there is a time to get forbidden status message error

### ISSUE THREAD

**Issue by veeppiaar** [un4gi/mBot#7]
Bot cannot be able to claim the missions even though there is a 10 seconds more time to get forbidden status error. Once the bot able to find newly polled missions, it cannot be able to claim any missions even after 10 seconds and printing error message for forbidden status error. Could you please investigate this issue?

**Comment by un4gi** [comment]
Seems like you're experiencing latency and someone else is claiming the mission before you are able to claim it.. if you are getting any specific error messages feel free to add them in a comment and I'll re-open this issue.
